name: Essentials
version: '${project.version}'
main: main.Main
api-version: 1.19
author: Dustin
commands:
  gm:
    description: Changes your gamemode
    usage: /gm <0/1/2/3>
    aliases: [gamemode]
  fly:
    description: Toggles flight
    usage: /fly
    aliases: [flight]
  heal:
    description: Heals you
    usage: /heal
    aliases: [healing]